services:
  - type: web
    name: splitwise-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: CLERK_ISSUER_URL
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3001
